# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160902_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton_text',
            new_name='question_text',
        ),
    ]
